name: Deploy on each commit
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🚀 rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        remote_host: cphost.hosttechno.com
        remote_port: 2303
        remote_user: devopshostserver
        remote_path: /home2/devopshostserver/public_html/
        remote_key: ${{ secrets.SSH_KEY }}
        switches: -avzr --delete 
