name: Deploy on each commit
on:
  push:
    branches:
    - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.CONFIG }} # ssh_config; optional
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: rsync over SSH
      run: rsync -avzr -e 'ssh -p 2303' ./ devopshostserver@cphost.hosttechno.com:/home2/devopshostserver/public_html/
